### PR TITLE
Expose temperature values from universal sensor

### PR DESCRIPTION
**Pull request by gaganpreet**
The universal sensor also has an inbuilt temperature sensor. I added some code to expose the values as a HA sensor.

I've set Black to autoformat my code on save, so the diff also includes some formatting changes in addition to new functionality.

### CODE REVIEW

**Comment by dynasticorpheus** [comment]
hi @gaganpreet Thanks for the PR but I really would like to stick to having one entity per (hardware) device. By coincidence the good news is that PR #11 should expose both temperature and pressure as attribute for universal as I also refactored respective function and therefore could easily add them.

Using a template sensor you could expose temperature / pressure as separate entity.

Let me know if this works as expected once merged, until then I will keep this PR open.

**Comment by dynasticorpheus** [comment]
@gaganpreet  Just did a new release. Can you confirm the temperature and pressure attribute are now added to universal?

**Comment by dynasticorpheus** [comment]
Implemented as attributes in 0.2.1

**Comment by gaganpreet** [comment]
I updated last night and had to first read up about template sensors to set up the temperature sensors and can report it worked as expected. Thanks!

For the next person who comes along and isn't familiar with template sensors, I added something like this to my `configuration.yaml`

```yaml
sensor:
  - platform: template
    sensors:
      bedroom_door_temp:
        friendly_name: "Bedroom door temperature"
        unit_of_measurement: '°C'
        value_template: "{{ '%+.1f'|format(state_attr('binary_sensor.gigaset_elements_universal_0324...', 'temperature')) }}"
      living_room_window_temp:
        friendly_name: "Living room window temperature"
        unit_of_measurement: '°C'
        value_template: "{{ '%+.1f'|format(state_attr('binary_sensor.gigaset_elements_universal_0355..', 'temperature')) }}"
        
```

**Pull request closed without merging**
